### ISSUE TITLE
Server crash on startup Guidebook-1.12.2-2.6.0

### ISSUE THREAD

**Issue by AdaraChristine** [gigaherz/Guidebook#56]
Guidebook-1.12.2-2.6.0
Minecraft: 1.12.2
Forge: 14.23.3.2697
Pack: Mystical Village 2

Time: 6/21/18 3:57 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: gigaherz/guidebook/client/BookRegistryEvent
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:602)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: gigaherz/guidebook/client/BookRegistryEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 31 more
Caused by: java.lang.ClassNotFoundException: gigaherz.guidebook.client.BookRegistryEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)

https://pastebin.com/2WTZAwLt

**Comment by gigaherz** [comment]
Hello, so far these crashes have been fixable by the mods using Guidebook lacking a dependency order.

See #48 and #51 for previous examples. I don't know which mod you are using that depends on Guidebook, but you might want to check if they have updates, and if not, report this to them.

**Comment by AdaraChristine** [comment]
The only mod i have that uses guidebook is Rockhounding which was just updated. Should i just link this to him in his Git?

**Comment by Wissi** [comment]
Not sure this is same or if this helps. 
Client crash when using guidebook. If mod is removed the modpack works fine. 
Happens more frequently with linux and MAC clients than with Windows clients.

Crashlog:  https://gist.github.com/Wissi/3b8508ba38ed10bb0b0d3d7f79404169

**Comment by gigaherz** [comment]
No that doesn't feel like the same crash, since this one is with ItemRegistered, which sounds like the embedded utility library wasn't properly extracted and loaded into the `memory_repo` folder (mods folder in older versions of forge)...

**Comment by Wissi** [comment]
It's been happening for some clients, but the majority are working fine. 
We haven't been able to find the common issues those specific clients might be having.

So is it a "fix" on your side that can be done?

Thanks for your hard work and quick response.

**Comment by gigaherz** [comment]
I can't think of anything I can do myself. I just declare that I have an embedded library, forge takes care of extracting it :/
